name: parkir_digital_bapenda
description: "Untuk Melakukan Pembayaran Parkir Secara Digital Di Kota Surabaya"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.9.2 # Pastikan versi SDK ini sesuai dengan instalasi lokalmu

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_dotenv: ^6.0.0
  dio: ^5.9.2
  flutter_bloc: ^9.1.1
  equatable: ^2.0.8
  dio_smart_retry: ^6.0.0
  chucker_flutter: ^1.9.1
  logger: ^2.4.0
  shared_preferences: ^2.2.2
  go_router: ^13.2.0
  json_annotation: ^4.11.0
  
  # --- Clean Architecture Utilities ---
  get_it: ^7.7.0 # Untuk Dependency Injection (Locator)
  dartz: ^0.10.1 # Untuk Functional Programming (Either<Failure, Success>)
  injectable: ^2.4.1 # Untuk Code Generation DI (Optional, jika menggunakan anotasi)
  
  # --- Core Features: Hardware & ML ---
  camera: ^0.11.0 # Stream kamera untuk on-device scan
  google_mlkit_text_recognition: ^0.14.0 # Engine On-Device OCR Google
  permission_handler: ^12.0.1 # Manajemen pop-up izin akses kamera
  flutter_secure_storage: ^10.0.0
  jwt_decoder: ^2.0.1
  sqflite: ^2.4.2
  path: ^1.9.1
  uuid: ^4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.9
  injectable_generator: ^2.6.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  fonts:
  - family: Poppins
    fonts:
      - asset: assets/fonts/Poppins-Regular.ttf
        weight: 400
      - asset: assets/fonts/Poppins-Medium.ttf
        weight: 500
      - asset: assets/fonts/Poppins-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Poppins-Bold.ttf
        weight: 700
      - asset: assets/fonts/Poppins-Italic.ttf
        style: italic
      - asset: assets/fonts/Poppins-ExtraBold.ttf
        weight: 800

  assets:
      - .env
      - assets/images/