// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVT2DjkThcm3RiEvMJkmLPg3c1-pHlk7Q',
    appId: '1:861812741883:web:84c2396e38358d4139c25e',
    messagingSenderId: '861812741883',
    projectId: 'tspark-bapenda-prod',
    authDomain: 'tspark-bapenda-prod.firebaseapp.com',
    storageBucket: 'tspark-bapenda-prod.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2dpZZ97d8kfEXrfGK5irmf2c57bFaGUw',
    appId: '1:861812741883:android:df5e52108111923c39c25e',
    messagingSenderId: '861812741883',
    projectId: 'tspark-bapenda-prod',
    storageBucket: 'tspark-bapenda-prod.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxxCj9uMESz7YSRRz56J8elJTrp2MKagE',
    appId: '1:861812741883:ios:d8a215521676d65439c25e',
    messagingSenderId: '861812741883',
    projectId: 'tspark-bapenda-prod',
    storageBucket: 'tspark-bapenda-prod.firebasestorage.app',
    iosBundleId: 'com.example.simulasiparkirdigital',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxxCj9uMESz7YSRRz56J8elJTrp2MKagE',
    appId: '1:861812741883:ios:d8a215521676d65439c25e',
    messagingSenderId: '861812741883',
    projectId: 'tspark-bapenda-prod',
    storageBucket: 'tspark-bapenda-prod.firebasestorage.app',
    iosBundleId: 'com.example.simulasiparkirdigital',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVT2DjkThcm3RiEvMJkmLPg3c1-pHlk7Q',
    appId: '1:861812741883:web:644ef20ab43d3b2839c25e',
    messagingSenderId: '861812741883',
    projectId: 'tspark-bapenda-prod',
    authDomain: 'tspark-bapenda-prod.firebaseapp.com',
    storageBucket: 'tspark-bapenda-prod.firebasestorage.app',
  );
}
